repos:
  - repo: local
    hooks:
      - id: commit-msg-check
        name: Check commit message format
        entry: ./scripts/check-commit-msg.sh
        language: script
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: secret-scan
        name: Block secrets in commits
        entry: ./scripts/check-secrets.sh
        language: script